apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: ENC[AES256_GCM,data:cPcYhLNPRPc=,iv:eyG9jHkfgvz8RZg2D4ezZD9Sq6v6Ii5Kh5NwBV2VQBk=,tag:u4lqlVjm6t6gwHK2psRNQg==,type:str]
    password: ENC[AES256_GCM,data:bh/sAoev5ObqFZFM1yHwKg==,iv:ISejVV4+Z9qdEUOYQ900ZgMnlaE+MgM2dqwOsTkybN0=,tag:w8g8j7nil8eMCsHHyAONIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-25T04:34:02Z"
    mac: ENC[AES256_GCM,data:LHX6AOtTiZdI+fUBEgzo6no0Oy1uOckI33+fP13tCMC4fB0EDkeNg7Om1RZZq8EIONQGCd3xpFjRtioxeN/W/ypBDee1qnjL+ZlOsroxYHUE04hFjs+/uWEQ9d25dJPNVFa6cxEsWTcF/40wXKvdWAnLTVv7wG0LbAn+HmiwfA0=,iv:KvPW/boT3bgMT5dBqU1TrEMKZ+NSHtQkhqEcAuiYRkc=,tag:fjz1eW03XJldFx2bGMFCXQ==,type:str]
    pgp:
        - created_at: "2022-07-25T04:33:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA213Cigz+h3dAQwAiuHHh4oC+W7CaBr4UfokXFWpwwnmp7r+nOn2RSSoSDvW
            Izx8mf+8gL3ne7em8yi4Yh1nfW/+SJI9qIJiCCKgesmkGd6GhgO9z+CmWYeE80Hq
            WCOZanR4e5RGpA3TB4laABHcysmhzC636CmlZ4mz9fosRsAYchNiRM0SRCVW5/jI
            NFZM39vS45LtlJ2ned4JWcILHoGk/w9qTGh/SZUx4YmL3mlMeZdkn+P/xkMQgTNj
            kgOXKT6/qvCqhD+9j77LvX1dl2tplpboQji9m/r3hiPscwCc53BlX2zg24I5pCEF
            K9Adn3nhypSpSMwxYcMbK0pEMF4xiJSe3SDDJfd/3MLVR6J9ir0wWU2x4taaDWj/
            SftZkD1x/2gnz3F7s12ay+LF2+PANocvDm+fo+Eh6urtV3XFU48Oj7ahRyQU6Gq5
            pYEnSV0sRxOtD4xtUibxBbAl1LyR0Z5tdsSws8XIXsgeHSvS836VhpKxwRTPml5F
            2C0GX7Tf6ddPVbqf10VY0l4BkwqYsNeZvNtZv/FxOOwa5DzGhR/e/T1T/8WVnr/q
            GCHQUyloXraz7nMxZmlg8w1k39sbQqEL17aILc8qX7ezZzaYp9NKGmLR5M0AtWVi
            Wacf/6qyHeMcSras6kXU
            =FMuA
            -----END PGP MESSAGE-----
          fp: 1A06FF1C036D1B656AC81953BB7B0CB4EDE69765
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
